server:
  port: 8080
  host: localhost

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: pyrolytics
  sslmode: disable
  max_conns: 10
  timeout: 5s
  read_only: false

nats:
  url: nats://localhost:4222
  reconnect_wait: 5s
  max_reconnects: 3
  connection_name: pyrolytics
  stream_name: pyrolytics
  stream_subjects: 
    - pyrolytics.>
  retention_policy: workqueue
  storage_type: file
  max_age: 24h
  replicas: 1

solana:
  network: devnet
  rpc_url: https://api.devnet.solana.com
  ws_url: wss://api.devnet.solana.com
  timeout: 30s
  max_retries: 3
  commitment: confirmed
